### ISSUE TITLE
Change Line 454 to add SZ

### ISSUE THREAD

**Issue by kcobbva** [shawntmeyer/WVD#1]
As written the script is validating DWORD and String.   However we're then changing String to SZ on line 464, which subsequently fails the validation and the OneDrive registry keys are not getting created.  I tested changing this line to read: [ValidateSet('DWORD','String','SZ')]   and subsequent tests ran without error and the OneDrive registry keys are now created.

**Comment by shawntmeyer** [comment]
Thank you Kevin. I added this possible option in the Validate set. Not sure why it worked this way.
